# Generated by Django 4.2 on 2023-06-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_order_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='کد')),
                ('discount', models.SmallIntegerField(default=0, verbose_name='میزان تخفیف')),
                ('quantity', models.SmallIntegerField(default=1, verbose_name='تعداد')),
            ],
        ),
    ]
